### ISSUE TITLE
direct access to $_GET/$_POST variables is not allowed

### ISSUE THREAD

**Issue by danmarsden** [jkonert/moodle-mod_groupformation#1]
these should be converted to using optional/required_param function calls as per Moodle coding and security guidelines. 
More info: https://docs.moodle.org/dev/Security#Don.27t_trust_any_input_from_users

**Comment by danmarsden** [comment]
looks like you missed a couple: 
https://github.com/jkonert/moodle-mod_groupformation/search?utf8=%E2%9C%93&q=%24_POST&type=Code

**Comment by ged-de** [comment]
seems like I forgot to commit analysis_view.php, thank you!

the other two were just comments, but deleted now.
